services:
  app:
    build: .
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/SimpleBank
      - SPRING_DATASOURCE_USERNAME=sereyvuth
      - SPRING_DATASOURCE_PASSWORD=vuth168
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.PostgreSQLDialect
      - JWT_SECRET=DTJ3sSzD52f7UBBnGppr2bo82BfHXjetX72yF6ANZrqjBKujjLpSSMHjdg==
      - JWT_ACCESS_TOKEN_EXPIRE_MINUTES=15
      - JWT_REFRESH_TOKEN_EXPIRE_MINUTES=7
      - JWT_ISSUER=SimpleBank
      - SERVER_PORT=8081
    depends_on:
      - db

  db:
    image: postgres:17
    environment:
      POSTGRES_DB: SimpleBank
      POSTGRES_USER: sereyvuth
      POSTGRES_PASSWORD: vuth168
    ports:
      - "1234:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./src/main/resources/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata: